@url = http://localhost:5000

### get all
GET {{url}}/users
Content-Type: application/json

### get single
GET {{url}}/users/62778d43abaaaec773828ffa
Content-Type: application/json

### create
POST {{url}}/users
Content-Type: application/json

{
    "name": "Peter",
    "hobby": "reading",
    "email": "julian@gmail.com",
    "city": "Bremen"
}

### delete
DELETE {{url}}/users/62ebd2a861f4f13795e6e843
Content-Type: application/json

### edit
PATCH {{url}}/users/62ebd2a861f4f13795e6e843
Content-Type: application/json

{
    "name": "Anne",
    "email": "anne@gmail.com"
}

### edit
PATCH {{url}}/users/62ebd2a561f4f13795e6e841
Content-Type: application/json

{
    "name": "Leon",
    "email": "leon@gmail.com",
}

### edit
PATCH {{url}}/users/62ebd2a861f4f13795e6e843
Content-Type: application/json

{
    "name": "Edward",
    "email": "edward@gmail.com",
}